Added copy, cut, past file actyions
rnbwdev/rnbw pull request #531
Opened 2023-12-22 17:03 UTC by VictoriaShyika

2023-12-22 20:37 UTC, jasonliu7040 requested changes
@VictoriaShyika 
it will be enough for you to implement `undo/redo` for `paste` action at
`/src/pages/main/processor/hooks/useFileTreeEvent.ts`
you can check my code and add `_move` like `_rename, _remove`
just write as you think, I will check and complete your work.
thanks.

2023-12-22 20:37 UTC, jasonliu7040 commented on src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
> +    // confirm files changes
@VictoriaShyika 
we can use `isUnsavedProject` helper instead of this.

2023-12-22 20:37 UTC, jasonliu7040 commented on src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
> +          payload: { uids },
@VictoriaShyika 
here the `payload` is not enough for undo/redo.
it should have `targetUid` info.
so like
payload: {
  uids : { orgUid, newUid } [ ]
}
with this format, we can implement undo/redo

2023-12-22 20:37 UTC, jasonliu7040 commented on src/_node/file/FileSystemApis.ts
> +  let newName = kind === "directory" ? name : `${name}.${ext}`;
@VictoriaShyika 
please remove `getFileNameAndExtensionFromFullname` from helpers.

2023-12-23 01:02 UTC, VictoriaShyika commented
undo/redo still in progress

2023-12-25 03:47 UTC, jasonliu7040 requested changes

2023-12-25 03:47 UTC, jasonliu7040 commented on src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
> +    const newName: string[] = await Promise.all(
let's name `newName` into `newNames`

2023-12-25 03:47 UTC, jasonliu7040 commented on src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
> +              newUid: `${targetNode.parentUid}/${
we shouldn't use the `/` character directly.
instead, we can use `_path.join` or `_path.sep`
you can check my code by searching. thanks.

2023-12-25 05:03 UTC, jasonliu7040 approved these changes
I will complete the rest.

2023-12-25 05:03 UTC, merged